apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-t3dv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-t3dv
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-t3dv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-t3dv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-t3dv
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kpjy-tenant/rhtap-demo-app/hacbs-test-project-t3dv@sha256:83dc3f3fa3d521dd85db2ea798c9f1b86b43fa135d2676135ac516b83e375cc9
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
