apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-t3dv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kpjy-tenant/rhtap-demo-app/hacbs-test-project-t3dv@sha256:83dc3f3fa3d521dd85db2ea798c9f1b86b43fa135d2676135ac516b83e375cc9
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
